### ISSUE TITLE
Do you try to re-implement binary function search task?

### ISSUE THREAD

**Issue by SicongCao** [simonlinyj/Graph-Matching-Networks#1]
请问您尝试复现过论文中提到的二元函数搜索任务吗，如果可以的话，可以留个联系方式

**Comment by Lin-Yijie** [comment]
The authors have not released their dataset hence we do not test the Binary Function Similarity Search tasks. I conjecture  that you could change the loss to "hanmming" in configure.py to train the model for this task.
