### ISSUE TITLE
GraphEncoder MLP edge

### ISSUE THREAD

**Issue by tathagatv** [simonlinyj/Graph-Matching-Networks#2]
In line 46 of [graphembeddingnetwork.py](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/main/graphembeddingnetwork.py), the iteration should be done with limit `len(self._edge_hidden_sizes)` while iterating over `self._edge_hidden_sizes`. Is using `len(self._node_hidden_sizes)` there a mistake?

**Comment by Lin-Yijie** [comment]
Yes, it is a mistake! I have fixed it right now.
Thanks~
