### ISSUE TITLE
How can I input my own graph data and compare it?

### ISSUE THREAD

**Issue by Lost-little-dinosaur** [simonlinyj/Graph-Matching-Networks#6]
Hi
I ran your train.py successfully, but I can't get an output and I want to use the script to compare my own graph data, how can I do? help me please~~.

**Comment by Lost-little-dinosaur** [comment]
and of course I gave you one star [doge]

**Comment by Lin-Yijie** [comment]
Hi~ You could construct your own dataset in [train.py](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/07f8cc51b608ca22bd27b149218d8bf584803cb1/train.py#L31). The output of the model is exactly a graph representation as shown in 66 line of [train.py.](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/07f8cc51b608ca22bd27b149218d8bf584803cb1/train.py#L66)

**Comment by Lost-little-dinosaur** [comment]
![image](https://user-images.githubusercontent.com/82520400/204706470-592cfd3f-d35e-455e-9e81-83855ab9827b.png)
I saw that I got the training set and the verification set in line 33, but it seemed to generate a seed, it just specified the limit range of the generated graph, and then generated an iterator through the GraphEditDistanceDataset class pairs function instead of input a concrete graph. 
![image](https://user-images.githubusercontent.com/82520400/204707092-4a93003c-90da-483f-9967-ae94e7884534.png)

This is a little bit complicated for me, can you give me a concrete example where you input an adjacency matrix of two graphs, and you get an adjacency matrix of their similarity as an output? I would really appreciate it......

**Comment by Lin-Yijie** [comment]
Hi dinosaur~
In this repo, we give an example graph similarity learning task for synthesis graph data. It is highly expected to build your own graph dataset like [GraphEditDistanceDataset](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/07f8cc51b608ca22bd27b149218d8bf584803cb1/dataset.py#L170). Similar to [def _get_graph](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/07f8cc51b608ca22bd27b149218d8bf584803cb1/dataset.py#L125), you might use networkx package to change the adjacency matrix into the networkx like graph structure.

**Comment by Lost-little-dinosaur** [comment]
Hi, sorry for my late reply, I am been busy with my final test last month...
I am a Chinese collage student and I am working on the comparation of two graph data, and I see the project you writed is very good. There are some questions I'd  like to ask you and I can pay for it.
I guess from your github name that you come from China, too. Can I have your QQ or Wechat? I think it will be much more convenienct if we can contact by QQ or Wechat.

**Comment by Lin-Yijie** [comment]
@Lost-little-dinosaur Hi dinosaur. You could contact me with linyijie.gm@gmail.com

**Comment by eleveneee** [comment]
hi，bro
Have you solved the problem of inputting your own graph?
Also, how was your graph generated?
Looking forward to your reply very much @Lost-little-dinosaur
