### ISSUE TITLE
use my oun graph data

### ISSUE THREAD

**Issue by eleveneee** [simonlinyj/Graph-Matching-Networks#7]
Hello, your code is really amazing!
But I encountered some problems during the operation. I wanted to input my own graph and get their similarity results, but I didn't see the specific input. What should I do?
Looking forward to your reply!

**Comment by Lin-Yijie** [comment]
Hi, which paper do you refer to?

**Comment by eleveneee** [comment]
Graph Matching Networks for Learning the Similarity of Graph Structured Objects @Lin-Yijie
