### ISSUE TITLE
Generate Graph

### ISSUE THREAD

**Issue by eleveneee** [simonlinyj/Graph-Matching-Networks#8]
Hello, first of all, thank you very much for your work!
May I ask how your image was generated from image?
You mentioned in the article that you referred to the article 'A Graph based approach for Kit recognition', but I haven't seen the code to generate the graph either.
I tried to convert from image to SVG and generate a graph myself, but when I input it into your code, the format always doesn't match.
How did you generate a graph from image? Can you provide the relevant code?

**Comment by Lin-Yijie** [comment]
The official code for Graph Matching Networks can be found at [https://github.com/deepmind/deepmind-research/tree/master/graph_matching_networks](https://github.com/deepmind/deepmind-research/tree/master/graph_matching_networks). If you have any questions or concerns about the experiments in the GMN paper, you may want to reach out to the author directly for more information.

**Comment by eleveneee** [comment]
Have you ever generated a graph from an image?

**Comment by Lin-Yijie** [comment]
Sorry, I do not understand what you exactly mean. In [COMMON](https://github.com/Lin-Yijie/Graph-Matching-Networks/tree/main/COMMON) we construct graph from the keypoints in the images from Pascal VOC, WILLOW, and Spair71k.

**Comment by eleveneee** [comment]
Okay, I'll try again

**Comment by eleveneee** [comment]
Excuse me, where did you obtain the gxl file in the dataset?
I searched online for KIMIA99 and MPEG7 datasets, but it seems that they only provided images and did not provide gxl image files.
I really hope to receive your reply
@Lin-Yijie

**Comment by Lin-Yijie** [comment]
Sorry, we do not use the KIMIA99 or MPEG7 datasets. What experiments do you refer to?
